name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate images' Dockerfiles
        run: ./dockerfiles.sh
      - name: Build Docker images
        run: ./build.sh
        env:
          DOCKER_REPOSITORY: 'instedd/nginx-rails'
          CURRENT_COMMIT: ${{ github.sha }}
      - name: Log into Docker
        run: docker login --username="${DOCKER_USER}" --password-stdin "${DOCKER_REGISTRY}" <<< "${DOCKER_PASS}"
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - name: Push commit-specific Docker images
        run: ./push.sh
        env:
          DOCKER_REPOSITORY: 'instedd/nginx-rails'
          CURRENT_COMMIT: ${{ github.sha }}
      - name: Push stable Docker images
        run: ./push.sh --stable
        if: ${{ github.ref == 'refs/head/master' }}
        env:
          DOCKER_REPOSITORY: 'instedd/nginx-rails'
          CURRENT_COMMIT: ${{ github.sha }}
