name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Test contents of github.ref
        run: echo "github.ref is $THE_GITHUB_REF <---"
        env:
          THE_GITHUB_REF: ${{ github.ref }}
      - name: Check if we got it right
        run: echo "Yes it works"
        if: ${{ github.ref == 'refs/head/test/github-actions' }}
      - name: Check alternative
        run: echo "It was the short one"
        if: ${{ github.ref == 'test/github-actions' }}
      
